# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
#check it now
version: 2.1
executors:
    my-executer:
      docker:
        - image: circleci/node:13.8.0
      working_directory: /tmp
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  flow:
      executor: my-executer
      steps:
        - run: mkdir -p workspace
        - persist_to_workspace:
            root: workspace
            paths:
              - echo-output
  save-hello-world:
    executor: my-executer
    steps:
      - checkout
      - run:
          name: "save hello world"
          command: echo "text to output here" > workspace/echo-output/output.txt
      - run: ls -lA
      - persist_to_workspace:
          root: /tmp/workspace/echo-output
          paths:
            - output.txt
  print_output_file:
    executor: my-executer
    steps:
      - checkout
      - run:
          name: "print output file"
          command: cat /tmp/workspace/echo-output/output.txt
      - attach_workspace:
          at: /tmp/workspace/echo-output
  # say-hello:
  #   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
  #   docker:
  #     - image: circleci/node:13.8.0
  #   # Add steps to the job
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#steps
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say hello"
  #         command: "echo Hello!"
  # say-world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "say world"
  #         command: "echo World"
  # say-my-name:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "say my name"
  #         command: "echo $My_Name"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      # - say-hello
      # - say-world:
      #     #requires: [say-hello]
      #     requires:
      #     - say-hello
      # - say-my-name:
      #     requires: [say-hello, say-world]
      - flow
      - save-hello-world
      - print_output_file:
          requires:
            - save-hello-world
